### ISSUE TITLE
AttributeError: 'server_info' object has no attribute 'player_list'

### ISSUE THREAD

**Issue by Diiam0nd** [pd00m/discord-csgo-bot#6]
Hey, love this project and I find it quite useful, I tried importing it into my bot as a cog, but it appears to give off the above error. Here is the code:

https://pastebin.com/xxqc7QXR

Any idea how to fix this? I have already downloaded all the required modules, this just seems to be an issue. 

Also, I am getting server down even though the server is online.

**Comment by pd00m** [comment]
Can you post the full error message? 
I can only assume what the issue is, please make sure the server_info class gets initialized before accessing the attributes.

**Comment by Diiam0nd** [comment]
Hey, here is the full error:

Ignoring exception in command server:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/Staff-Bot/cogs/csgo.py", line 102, in server
    for player in server_info.player_list:
AttributeError: 'server_info' object has no attribute 'player_list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'server_info' object has no attribute 'player_list'

Also, is it possible to use this for multiple servers?

**Comment by pd00m** [comment]
I think the server_info class is not initialized when you are accessing the properties of that class. They get initialized after calling the class constructor.

Try this:

``` 
class CSGO(commands.Cog):
 
    def __init__(self, bot):
        with open("config.json") as json_file:
        self.config = json.load(json_file)
        self.server_info = server_info(self.config)

        self.bot = bot
```



yes, it should be possible to run multiple instances, either if you use the provided dockerfile and host multiple containers or if you want to integrate it in your own program, simply create multiple instances of the server_info class and provide multiple configs for each instance

```
self.server_info_a = server_info(config_a)
self.server_info_b = server_info(config_b)
```

**Comment by Diiam0nd** [comment]
Hey mate, 

The above issue is fixed. I attempted to do it on this IP and Port, but it kept returning the server down message even when the server was online. I tried this out on a completely fresh bot and just imported the repo and got the same issue. I did some tests and can confirm the bot is reading the config file successfully, so I'm not sure what the issue is. 

IP: 202.130.34.223
Port: 27030

Is this an issue with the server specifically? I tried this on other servers in the same region and got the same issue. 

If it helps, I'm using replit.com to host my bot(s). 

Thank you.
